"""Website Intelligence AI - Web Crawler Module

This module handles web crawling with intelligent planning using LLM agents.
It determines the best crawling strategy for a given URL and executes the crawl.
"""

import asyncio
from datetime import datetime
import json
from crawl4ai import AsyncUrlSeeder, AsyncWebCrawler, CrawlerRunConfig, PruningContentFilter,SeedingConfig
from crawl4ai.deep_crawling import BFSDeepCrawlStrategy
from crawl4ai.content_scraping_strategy import LXMLWebScrapingStrategy
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator
from pydantic import BaseModel, Field
from llm_model import llm
import os
from dotenv import load_dotenv
load_dotenv(override=True)

print("[CRAWLER] Module loaded successfully")

# ─── Get total active pages ───────────────────────────────────────────

async def get_total_active_pages(domain_url: str) -> int:
    """Discovers total active pages on a website using sitemap and crawl4ai seeding.
    
    Args:
        domain_url: The base URL of the website to scan
        
    Returns:
        Integer count of active pages found, or 0 if seeding fails
    """
    print(f"[CRAWLER] Discovering active pages for: {domain_url}")
    try:
        print(f"[CRAWLER] Initializing URL seeder with sitemap+cc strategy...")
        config = SeedingConfig(source="sitemap+cc", live_check=True, concurrency=20)
        async with AsyncUrlSeeder() as seeder:
            print(f"[CRAWLER] Fetching all discovered URLs...")
            discovered_urls = await seeder.urls(domain_url, config)
            print(f"[CRAWLER] Total discovered URLs: {len(discovered_urls)}")
            
            # Filter for only valid/active pages
            active_pages = [url for url in discovered_urls if url.get("status") == "valid"]
            print(f"[CRAWLER] Active pages found: {len(active_pages)}")
            return len(active_pages)
    except Exception as e:
        print(f"[CRAWLER] ❌ URL seeding failed: {e}, returning 0")
        return 0
    
# ─── Agent output schema ───────────────────────────────────────────


class CrawlPlan_config(BaseModel):
    """Configuration schema for AI-planned crawling strategy.
    
    Generated by the LLM agent to define how a website should be crawled.
    """
    site_type: str = Field(..., description="One of: docs, ecommerce, blog, support, unknown")
    max_depth: int = Field(..., description="How deep to crawl. 1=surface only, 3=deep docs site")
    max_pages: int = Field(..., description="Max pages to crawl. Small site=20, large docs=100")
    pruning_threshold: float = Field(..., description="Threshold for pruning content. 0.3 to 0.8")
    notes: str = Field(..., description="Any specific instructions for crawling this site")

print(f"[CRAWLER] Using shared LLM instance from llm_model")


async def plan_crawl(url:str) -> CrawlPlan_config:
    """
    Agent inspects the URL and decides how to crawl it.
    This is the 'brain' — runs before any crawling starts.
    
    Returns a CrawlPlan_config with optimized crawling parameters.
    """
    print(f"[CRAWLER] === PLANNING CRAWL STRATEGY ===")
    print(f"[CRAWLER] Target URL: {url}")
    
    print(f"[CRAWLER] Configuring LLM for structured output...")
    structured_llm = llm.with_structured_output(CrawlPlan_config)

    print(f"[CRAWLER] Getting page count to inform strategy...")
    number_of_pages = await get_total_active_pages(url)

    print(f"[CRAWLER] Invoking LLM agent to create crawl plan...")
    response = structured_llm.invoke(f"""
    Analyze this website URL and create best crawling strategy.

    URL: {url}

    As per the latest scan, this website has approximately {number_of_pages} active pages.

    Rules:
    - Documentation sites (docs., /docs, /guide, /reference): depth=3, pages=80
    - E-commerce sites: depth=2, pages=50, likely JS-heavy
    - Blogs or marketing sites: depth=2, pages=30
    - Support/help centers: depth=2, pages=60
    - Unknown or simple sites: depth=1, pages=20
    - Any site using React/Next.js/Vue likely needs JS rendering

    Analyze the URL pattern and decide:

    - site_type (docs, ecommerce, blog, support, app)
    - max_depth (1-5)
    - max_pages (20-500)
    - pruning_threshold (0.3 to 0.8)
    - notes (any specific instructions for crawling this site)

    Return structured output only.
    """)
    print(f"[CRAWLER] ✓ Agent decision received")
    print(f"[CRAWLER]   Site Type: {response.site_type}")
    print(f"[CRAWLER]   Max Depth: {response.max_depth}")
    print(f"[CRAWLER]   Max Pages: {response.max_pages}")
    print(f"[CRAWLER]   Pruning Threshold: {response.pruning_threshold}")
    print(f"[CRAWLER]   Notes: {response.notes}")
    return response

# ─── Main crawl function ───────────────────────────────────────────


async def crawl_url(start_url:str) -> list[dict]:

    """
    Crawls a URL using agent-decided configuration.
    Agent runs first, then Crawl4AI executes the strategy.
    
    Returns a list of dictionaries containing crawled page data.
    """
    print(f"[CRAWLER] === STARTING CRAWL ===")
    print(f"[CRAWLER] Start URL: {start_url}")
    
    # Get crawl strategy from LLM agent
    print(f"[CRAWLER] Requesting crawl strategy from LLM agent...")
    try:
        plan = await plan_crawl(start_url)
        print(f"[CRAWLER] ✓ Crawl plan created successfully")
    except Exception as e:
        print(f"[CRAWLER] ❌ Agent planning failed: {e}")
        print(f"[CRAWLER] Using fallback configuration...")
        plan = CrawlPlan_config(
            site_type="default",
            max_depth=2,
            max_pages=100,
            pruning_threshold=0.45,
            notes="fallback"
        )

    print(f"[CRAWLER] Final crawl plan configured")

    # Configure content pruning filter
    print(f"[CRAWLER] Setting up content pruning filter (threshold: {plan.pruning_threshold})...")
    prune_filter = PruningContentFilter(
        threshold=plan.pruning_threshold,           
        threshold_type="dynamic",  
        min_word_threshold=50      
    )

    # Configure markdown generation
    print(f"[CRAWLER] Initializing markdown generator...")
    md_generator = DefaultMarkdownGenerator(content_filter=prune_filter)

    # Configure crawler with BFS deep crawl strategy
    print(f"[CRAWLER] Creating crawler configuration with BFS strategy...")
    config = CrawlerRunConfig(
        deep_crawl_strategy=BFSDeepCrawlStrategy(
            max_depth=plan.max_depth, 
            include_external=False,
            max_pages=plan.max_pages
        ),
        scraping_strategy=LXMLWebScrapingStrategy(),
        verbose=False,
        markdown_generator=md_generator,
        scan_full_page=True
    )
    print(f"[CRAWLER] ✓ Crawler configuration ready")
    
    try:

        pages = []
        print(f"[CRAWLER] Initializing AsyncWebCrawler...")
        async with AsyncWebCrawler() as crawler:

            print(f"[CRAWLER] ⏳ Starting crawl execution.....")
            print(f"[CRAWLER] Max depth: {plan.max_depth}, Max pages: {plan.max_pages}")

            # Execute the crawl
            results = await crawler.arun(start_url, config=config)

            print(f"[CRAWLER] ✓ Crawl complete. Total results: {len(results)}")

            count = 0
            failed_count = 0

            for result in results:  
                # Skip pages without successful crawls or markdown content
                if not result.success or not result.markdown:
                    failed_count += 1
                    continue
                    
                # Build page data with content and metadata
                data = {
                    "url": result.url,
                    "content": result.markdown.fit_markdown,
                    "metadata": result.metadata,
                    "timestamp":  datetime.now().isoformat(),
                    "crawl_config" : {
                        "site_type": plan.site_type,
                        "max_depth": plan.max_depth,
                        "max_pages": plan.max_pages,
                        "pruning_threshold": plan.pruning_threshold,
                        "notes": plan.notes
                    }
                }
                
                pages.append(data)
                count += 1

                if count % 10 == 0 or count == 1:
                    print(f"[CRAWLER] ✓ Processed {count} pages (Failed: {failed_count})")

        print(f"[CRAWLER] === CRAWL COMPLETE ===")
        print(f"[CRAWLER] Successfully saved: {count} pages")
        print(f"[CRAWLER] Failed: {failed_count} pages")
        return pages

    except Exception as e:
        print(f"[CRAWLER] ❌ Error during crawling: {e}")
        print(f"[CRAWLER] Returning empty list")
        return []
