"""Website Intelligence AI - Web Crawler Module

This module handles web crawling with intelligent planning using LLM agents.
It determines the best crawling strategy for a given URL and executes the crawl.
"""

from datetime import datetime
from crawl4ai import AsyncUrlSeeder, AsyncWebCrawler, CrawlerRunConfig, PruningContentFilter,SeedingConfig
from crawl4ai.deep_crawling import BFSDeepCrawlStrategy
from crawl4ai.content_scraping_strategy import LXMLWebScrapingStrategy
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator
from pydantic import BaseModel, Field
from llm_model import llm
from utils.logger import get_logger
from dotenv import load_dotenv

load_dotenv(override=True)

logger = get_logger("CRAWLER")

# ============================================================
# PAGE DISCOVERY
# ============================================================

async def get_total_active_pages(domain_url: str) -> int:
    """Discovers total active pages on a website using sitemap and crawl4ai seeding.
    
    Args:
        domain_url: The base URL of the website to scan
        
    Returns:
        Integer count of active pages found, or 0 if seeding fails
    """
    logger.info("Discovering pages for: %s", domain_url)
    try:
        config = SeedingConfig(source="sitemap+cc", live_check=True, concurrency=20)
        async with AsyncUrlSeeder() as seeder:
            discovered_urls = await seeder.urls(domain_url, config)
            active_pages = [url for url in discovered_urls if url.get("status") == "valid"]
            logger.info("Found %d active pages for %s", len(active_pages), domain_url)
            return len(active_pages)
    except Exception as e:
        logger.error("URL seeding failed for %s", domain_url, exc_info=True)
        return 0

# ============================================================
# CRAWL PLANNING
# ============================================================

class CrawlPlan_config(BaseModel):
    """Configuration schema for AI-planned crawling strategy.
    
    Generated by the LLM agent to define how a website should be crawled.
    """
    site_type: str = Field(..., description="One of: docs, ecommerce, blog, support, unknown")
    max_depth: int = Field(..., description="How deep to crawl. 1=surface only, 3=deep docs site")
    max_pages: int = Field(..., description="Max pages to crawl. Small site=20, large docs=100")
    pruning_threshold: float = Field(..., description="Threshold for pruning content. 0.3 to 0.8")
    notes: str = Field(..., description="Any specific instructions for crawling this site")


async def plan_crawl(url: str) -> CrawlPlan_config:
    """
    Agent inspects the URL and decides how to crawl it.
    This is the 'brain' — runs before any crawling starts.
    
    Returns a CrawlPlan_config with optimized crawling parameters.
    """
    logger.info("Planning crawl strategy for: %s", url)
    
    try:
        structured_llm = llm.with_structured_output(CrawlPlan_config)
        number_of_pages = await get_total_active_pages(url)
        
        response = structured_llm.invoke(f"""
    Analyze this website URL and create best crawling strategy.

    URL: {url}

    As per the latest scan, this website has approximately {number_of_pages} active pages.

    Rules:
    - Documentation sites (docs., /docs, /guide, /reference): depth=3, pages=80
    - E-commerce sites: depth=2, pages=50, likely JS-heavy
    - Blogs or marketing sites: depth=2, pages=30
    - Support/help centers: depth=2, pages=60
    - Unknown or simple sites: depth=1, pages=20
    - Any site using React/Next.js/Vue likely needs JS rendering

    Analyze the URL pattern and decide:

    - site_type (docs, ecommerce, blog, support, app)
    - max_depth (1-5)
    - max_pages (20-500)
    - pruning_threshold (0.3 to 0.8)
    - notes (any specific instructions for crawling this site)

    Return structured output only.

    {{

    "site_type": str = Field(..., description="One of: docs, ecommerce, blog, support, unknown")
    "max_depth": int = Field(..., description="How deep to crawl. 1=surface only, 3=deep docs site")
    "max_pages": int = Field(..., description="Max pages to crawl. Small site=20, large docs=100")
    "pruning_threshold": float = Field(..., description="Threshold for pruning content. 0.3 to 0.8")
    "notes": str = Field(..., description="Any specific instructions for crawling this site")

    }}

    """)
        
        logger.debug("Crawl plan: type=%s depth=%d pages=%d threshold=%.2f", 
                     response.site_type, response.max_depth, response.max_pages, response.pruning_threshold)
        return response
        
    except Exception as e:
        logger.error("Crawl planning failed for %s", url, exc_info=True)
        raise

# ─── Main crawl function ───────────────────────────────────────────


async def crawl_url(start_url: str) -> list[dict]:
    """
    Crawls a URL using agent-decided configuration.
    Agent runs first, then Crawl4AI executes the strategy.
    
    Returns a list of dictionaries containing crawled page data.
    """
    logger.info("Starting crawl: %s", start_url)
    
    try:
        plan = await plan_crawl(start_url)
    except Exception as e:
        logger.warning("Crawl planning failed, using fallback: %s", e)
        plan = CrawlPlan_config(
            site_type="default",
            max_depth=2,
            max_pages=100,
            pruning_threshold=0.45,
            notes="fallback"
        )

    prune_filter = PruningContentFilter(
        threshold=plan.pruning_threshold,           
        threshold_type="dynamic",  
        min_word_threshold=50      
    )
    md_generator = DefaultMarkdownGenerator(content_filter=prune_filter)

    config = CrawlerRunConfig(
        deep_crawl_strategy=BFSDeepCrawlStrategy(
            max_depth=plan.max_depth, 
            include_external=False,
            max_pages=plan.max_pages
        ),
        scraping_strategy=LXMLWebScrapingStrategy(),
        verbose=False,
        markdown_generator=md_generator,
        scan_full_page=True
    )
    
    try:
        pages = []
        logger.debug("Crawler config ready: type=%s depth=%d pages=%d", 
                     plan.site_type, plan.max_depth, plan.max_pages)
        
        async with AsyncWebCrawler() as crawler:
            results = await crawler.arun(start_url, config=config)
            
            count = 0
            failed_count = 0
            skipped_count = 0

            for result in results:
                if not result.success:
                    failed_count += 1
                    continue
                
                if not result.markdown:
                    skipped_count += 1
                    continue
                    
                data = {
                    "url": result.url,
                    "content": result.markdown.fit_markdown,
                    "metadata": result.metadata,
                    "timestamp": datetime.now().isoformat(),
                    "crawl_config": {
                        "site_type": plan.site_type,
                        "max_depth": plan.max_depth,
                        "max_pages": plan.max_pages,
                        "pruning_threshold": plan.pruning_threshold,
                        "notes": plan.notes
                    }
                }
                
                pages.append(data)
                count += 1

        logger.info("Crawl complete: %d success, %d failed, %d skipped out of %d results", 
                    count, failed_count, skipped_count, len(results))
        return pages

    except Exception as e:
        logger.error("Crawl execution failed for %s", start_url, exc_info=True)
        return []
